import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-[100vh] bg-white border-[5px] text-black`}
      >
        <header className="border-[2px] border-[red]">
          <div className="flex gap-2 p-5">
            <Link href="/">홈</Link>
            <Link href="/about">소개</Link>
          </div>
        </header>
        <main className="border-[2px] border-[blue]">
          {children} Lorem ipsum dolor sit amet consectetur adipisicing elit.
          Voluptas dolore dolor unde eligendi modi labore laboriosam repellendus
          maxime. In impedit perferendis voluptatem animi eius quis repellat,
          soluta provident atque
        </main>
        <footer className="border-[2px] border-[green]">Copyright 2025.</footer>
      </body>
    </html>
  );
}
