/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/product": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 주문 요청
         * @description 주문 요청이 데이터베이스에 저장됩니다.
         */
        post: operations["order"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/delivery/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 반환 데이터 */
        Empty: Record<string, never>;
        /** @description 결과 반환용 객체 */
        ResultEmpty: {
            /**
             * Format: int32
             * @description 상태 코드
             */
            statusCode: number;
            /** @description 클라 전달용 메시지 */
            message: string;
            data: components["schemas"]["Empty"];
        };
        ProductCreateRequest: Record<string, never>;
        /** @description 반환 데이터 */
        ProductCreateResponse: Record<string, never>;
        /** @description 결과 반환용 객체 */
        ResultProductCreateResponse: {
            /**
             * Format: int32
             * @description 상태 코드
             */
            statusCode: number;
            /** @description 클라 전달용 메시지 */
            message: string;
            data: components["schemas"]["ProductCreateResponse"];
        };
        OrderRequest: Record<string, never>;
        /** @description 반환 데이터 */
        OrderResponse: {
            /**
             * Format: int64
             * @description 주문 ID
             */
            id: number;
            /** @description 주문 이름 */
            name: string;
        };
        /** @description 결과 반환용 객체 */
        ResultOrderResponse: {
            /**
             * Format: int32
             * @description 상태 코드
             */
            statusCode: number;
            /** @description 클라 전달용 메시지 */
            message: string;
            data: components["schemas"]["OrderResponse"];
        };
        /** @description 반환 데이터 */
        ProductInfoResponse: Record<string, never>;
        /** @description 결과 반환용 객체 */
        ResultListProductInfoResponse: {
            /**
             * Format: int32
             * @description 상태 코드
             */
            statusCode: number;
            /** @description 클라 전달용 메시지 */
            message: string;
            /** @description 반환 데이터 */
            data: components["schemas"]["ProductInfoResponse"][];
        };
        /** @description 반환 데이터 */
        DeliveryResponse: Record<string, never>;
        /** @description 결과 반환용 객체 */
        ResultListDeliveryResponse: {
            /**
             * Format: int32
             * @description 상태 코드
             */
            statusCode: number;
            /** @description 클라 전달용 메시지 */
            message: string;
            /** @description 반환 데이터 */
            data: components["schemas"]["DeliveryResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["ResultProductCreateResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["ResultEmpty"];
                };
            };
        };
    };
    order: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["ResultOrderResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["ResultEmpty"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["ResultListProductInfoResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["ResultEmpty"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["ResultListDeliveryResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["ResultEmpty"];
                };
            };
        };
    };
}
